### ISSUE TITLE
实现 隐藏小程序scroll-view的滚动条

### ISSUE THREAD

**Issue by letshare** [letshare/blog#5]
网上搜了2个方案：

    1. 隐藏样式

    ```css
    ::-webkit-scrollbar{
    width: 0;
    height: 0;
    color: transparent;
    }
    ```
    实际上很坑，会造成容器坍塌，高度撑不起来，去掉width: 0和height: 0也不行。因此尝试了另外一种方式。

    2. scroll-view的滚动条设置在视图外
    
    注意：scroll-view的滚动条是贴着padding-right的

    这个方案的原理了是多加2层，在scroll-view外加一层包裹view，设置overflow：hidden
    然后scroll-view的width为calc(100%+30px)，这样出现的滚动条就会出现在视图外，但父层的overflow：hidden，所以整个页面的横向不会出现滚动条。
    scroll-view多加了30px，那么为了保持跟原有样式一样，就得在加了的内层设置margin-right:30px
